language: php
sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
  - php: 5.6

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer install --prefer-dist --no-interaction

script: phpunit
